<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KosmosERP.Database\KosmosERP.Database.csproj" />
    <ProjectReference Include="..\KosmosERP.Models\KosmosERP.Models.csproj" />
    <ProjectReference Include="..\KosmosERP.BusinessLayer\KosmosERP.BusinessLayer.csproj" />
  </ItemGroup>

</Project>
