apiVersion: v1
kind: Secret
metadata:
  name: kosmos-erp-db-secret
  namespace: kosmos-demo
type: Opaque
stringData:
  root-password: ""
  username: ""
  password: ""
  connection-string: "Server=;Port=3306;Database=kosmos_erp;User=;Password=;allowPublicKeyRetrieval=true;"
---
apiVersion: v1
kind: Secret
metadata:
  name: kosmos-erp-hangfire-secret
  namespace: kosmos-demo
type: Opaque
stringData:
  connection-string: "Server=;Port=3306;Database=hangfire;User=;Password=;allowPublicKeyRetrieval=true;"
---
apiVersion: v1
kind: Secret
metadata:
  name: kosmos-erp-api-secret
  namespace: kosmos-demo
type: Opaque
stringData:
  password: ""
  username: ""
  private-key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: kosmos-erp-stripe-secret
  namespace: kosmos-demo
type: Opaque
stringData:
  api-key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: kosmos-erp-keycloak-secret
  namespace: kosmos-demo
type: Opaque
stringData:
  client-secret: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: kosmos-erp-superset-secret
  namespace: kosmos-demo
type: Opaque
stringData:
  secret-key: "superset-secret-key"
  database-uri: "postgresql://USERNAME:PASSWORD@POSTGRESS_SERVER:5432/superset"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: kosmos-demo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    INSERT_SECRET_BASE64_ENCODED_DOCKER_CONFIG_JSON_HERE
---
apiVersion: v1
kind: Secret
metadata:
  name: kosmos-erp-postgres-secret
  namespace: kosmos-demo
type: Opaque
stringData:
  username: ""
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: kosmos-erp-redis-secret
  namespace: kosmos-demo
type: Opaque
stringData:
  password: ""
